### ISSUE TITLE
Crash with ticking entity

### ISSUE THREAD

**Issue by Maxi90909** [FoggyHillside/End-s-Delight#33] opened 2024-06-26 18:17 UTC
https://pastebin.com/qdmLsL8X

Crash upon joining a world

**Comment by FoggyHillside** [comment] 2024-06-27 08:01
Try using ends_delight-1.20.1-2.2

**Comment by gnilobaiter** [comment] 2024-06-27 11:07
[crash-2024-06-27_14.04.25-server.txt](https://github.com/user-attachments/files/16012447/crash-2024-06-27_14.04.25-server.txt)

Same crash like: 

`...cn.foggyhillside.ends_delight.item.DragonToothKnifeEvent$KnifeEvents.onAttackEndMobs(DragonToothKnifeEvent.java:17)...`

**Comment by FoggyHillside** [comment] 2024-06-28 11:51
Try Neruina mod, or I remembered that Forge has a "removeErroringTileEntities" option in forge.cfg file, turn it to "true", then turn it to "false" after it worked. I'm not sure if Fabric has this option.
I can't reproduce this issue yet, so I'm not sure about whether it is fixed in the existed versions. I'll release some versions for test, and if you want to help test these versions, please give me some feedbacks. It will help a lot, thanks!

**Comment by unilock** [comment] 2024-06-28 15:17
The issue is that the mod does not check that the attacking entity is an instance of `LivingEntity` before casting it to that.

https://github.com/FoggyHillside/End-s-Delight/blob/f04e5ebcf4506f83df19fdd1aa63ecb451e1b61a/src/main/java/cn/foggyhillside/ends_delight/item/DragonToothKnifeEvent.java#L23

This can be easily fixed, by changing

```java
if (id.equals(endMob)) {
    LivingEntity attacker = (LivingEntity) source.getAttacker();
```

to

```java
if (id.equals(endMob) && source.getAttacker() instanceof LivingEntity attacker) {
```

**Comment by FoggyHillside** [comment] 2024-06-28 16:31
Thanks for your help!

**Comment by ShamHyper** [comment] 2024-06-29 04:05
> Try Neruina mod, or I remembered that Forge has a "removeErroringTileEntities" option in forge.cfg file, turn it to "true", then turn it to "false" after it worked. I'm not sure if Fabric has this option. I can't reproduce this issue yet, so I'm not sure about whether it is fixed in the existed versions. I'll release some versions for test, and if you want to help test these versions, please give me some feedbacks. It will help a lot, thanks!

I'm using fabric

**Comment by gnilobaiter** [comment] 2024-06-29 04:06
![image](https://github.com/FoggyHillside/End-s-Delight/assets/104412752/dd609f63-5bfc-4c54-a6ba-88dc2b9e6d45)
Fixed in this version?

**Comment by FoggyHillside** [comment] 2024-06-29 05:57
Yes

**Closed as completed** 2024-07-02 23:25 UTC
